version: '3.8'

services:
   app:
      image: phonebook-front-prod
      build:
        context: "C:\\Users\\verap\\part12-containers-applications-main\\phonebook\\phonebook_frontend"
        dockerfile: Dockerfile
      container_name: phonebook-app-ui
      env_file: "C:\\Users\\verap\\part12-containers-applications-main\\phonebook\\phonebook_frontend\\.env"
      depends_on:
       - server

   server:                   
      image: phonebook-back-prod
      build:
        context: "C:\\Users\\verap\\part12-containers-applications-main\\phonebook\\phonebook_backend" 
        dockerfile: Dockerfile
      container_name: phonebook-app-server
      env_file: "C:\\Users\\verap\\part12-containers-applications-main\\phonebook\\phonebook_backend\\.env"
      depends_on:
        - mongo 

   mongo:
     image: mongo
     ports:
      - 3456:27017
     container_name: phonebook-app-db
  
   nginx:
      image: nginx:1.20.1
      volumes:
        - "C:\\Users\\verap\\part12-containers-applications-main\\phonebook\\nginx.conf:/etc/nginx/nginx.conf:ro"
      ports:
        - 8080:80
      container_name: phonebook-app-reverse-proxy
      depends_on:
       - app 
       - server
