version: '3.8'

services:
   redis:
    image: redis
    ports:
      - "6379:6379"
    command: ['redis-server', '--appendonly', 'yes']
    volumes:
      - "C:\\Users\\verap\\part12-containers-applications-main\\todo-app\\todo-backend\\redis_data:/data"
  
   mongo:
    image: mongo
    ports:
     - 3456:27017
    volumes: 
     - "C:\\Users\\verap\\part12-containers-applications-main\\todo-app\\todo-backend\\mongo\\mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js"
     - "C:\\Users\\verap\\part12-containers-applications-main\\todo-app\\todo-backend\\mongo_data:/data/db"

   nginx:
      image: nginx:1.20.1
      volumes:
       - "C:\\Users\\verap\\part12-containers-applications-main\\todo-app\\nginx.conf:/etc/nginx/nginx.conf:ro"
      ports:
        - 8080:80
      depends_on:
       - app 
       - server

   app:
      image: todo-front-dev
      build:
        context: "C:\\Users\\verap\\part12-containers-applications-main\\todo-app\\todo-frontend"
        dockerfile: dev.Dockerfile
      container_name: todo-app-ui-dev
      volumes:
       - "C:\\Users\\verap\\part12-containers-applications-main\\todo-app\\todo-frontend\\:/usr/src/app" 
      env_file: "C:\\Users\\verap\\part12-containers-applications-main\\todo-app\\todo-frontend\\.env"
      environment:
       - WDS_SOCKET_PORT=0
       - WATCHPACK_POLLING=true 
      depends_on:
       - server

   debug-helper:
      image: busybox
      container_name: todo-app-debug-helper

   server:                   
      image: todo-back-dev
      build:
        context: "C:\\Users\\verap\\part12-containers-applications-main\\todo-app\\todo-backend"
        dockerfile: dev.Dockerfile
      container_name: todo-app-server-dev
      volumes:
       - C:\\Users\\verap\\part12-containers-applications-main\\todo-app\\todo-backend\\:/usr/src/app
      env_file: "C:\\Users\\verap\\part12-containers-applications-main\\todo-app\\todo-backend\\.env"
      depends_on:
       - mongo 
       - redis

volumes:
  mongo_data:
