version: '3.8'

services:
   redis:
    image: redis
    ports:
      - "6379:6379"
    command: ['redis-server', '--appendonly', 'yes']
    volumes:
      - "C:\\Users\\secret\\part12-containers-applications-main\\todo-app\\todo-backend\\redis_data:/data"
    env_file: "C:\\Users\\secret\\part12-containers-applications-main\\todo-app\\todo-backend\\.env"

   mongo:
    image: mongo
    ports:
     - 3456:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
    volumes: 
     - "C:\\Users\\secret\\part12-containers-applications-main\\todo-app\\todo-backend\\mongo\\mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js"
     - "C:\\Users\\secret\\part12-containers-applications-main\\todo-app\\todo-backend\\mongo_data:/data/db"
    env_file: "C:\\Users\\secret\\part12-containers-applications-main\\todo-app\\todo-backend\\.env"

volumes:
  mongo_data:

